//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace food_truck.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class falcomtccEntities2 : DbContext
    {
        public falcomtccEntities2()
            : base("name=falcomtccEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<jn_trabalho> jn_trabalho { get; set; }
        public DbSet<tb_caixa> tb_caixa { get; set; }
        public DbSet<tb_cliente> tb_cliente { get; set; }
        public DbSet<tb_conta> tb_conta { get; set; }
        public DbSet<tb_escala> tb_escala { get; set; }
        public DbSet<tb_estoque> tb_estoque { get; set; }
        public DbSet<tb_funcinario> tb_funcinario { get; set; }
        public DbSet<tb_holerite> tb_holerite { get; set; }
        public DbSet<tb_login> tb_login { get; set; }
        public DbSet<tb_logistica> tb_logistica { get; set; }
        public DbSet<tb_pedido_compra> tb_pedido_compra { get; set; }
        public DbSet<tb_pedido_compra_item> tb_pedido_compra_item { get; set; }
        public DbSet<tb_pedido_venda> tb_pedido_venda { get; set; }
        public DbSet<tb_pedido_venda_item> tb_pedido_venda_item { get; set; }
        public DbSet<tb_produto> tb_produto { get; set; }
        public DbSet<tb_produto_venda> tb_produto_venda { get; set; }
        public DbSet<tb_salario> tb_salario { get; set; }
        public DbSet<tb_taxa> tb_taxa { get; set; }
        public DbSet<tb_fornecedor> tb_fornecedor { get; set; }
    }
}
