//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace food_truck.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_funcinario
    {
        public tb_funcinario()
        {
            this.jn_trabalho = new HashSet<jn_trabalho>();
            this.tb_escala = new HashSet<tb_escala>();
            this.tb_holerite = new HashSet<tb_holerite>();
            this.tb_login = new HashSet<tb_login>();
            this.tb_pedido_venda = new HashSet<tb_pedido_venda>();
            this.tb_salario = new HashSet<tb_salario>();
            this.tb_taxa = new HashSet<tb_taxa>();
        }
    
        public int id_funcionario { get; set; }
        public string nm_funcionario { get; set; }
        public string tb_sobrenome { get; set; }
        public string tb_apelido { get; set; }
        public Nullable<System.DateTime> dt_nascimento { get; set; }
        public string tb_sexo { get; set; }
        public Nullable<decimal> vl_transpote { get; set; }
        public Nullable<decimal> vl_salario { get; set; }
        public string tb_RG { get; set; }
        public string tb_CPF { get; set; }
        public string nm_endereco { get; set; }
        public string nm_bairro { get; set; }
        public string nm_cidade { get; set; }
        public string nm_numero { get; set; }
        public Nullable<System.DateTime> dt_admissao { get; set; }
        public Nullable<System.DateTime> dt_demissao { get; set; }
        public string tl_celular { get; set; }
        public string tb_fixo { get; set; }
    
        public virtual ICollection<jn_trabalho> jn_trabalho { get; set; }
        public virtual ICollection<tb_escala> tb_escala { get; set; }
        public virtual ICollection<tb_holerite> tb_holerite { get; set; }
        public virtual ICollection<tb_login> tb_login { get; set; }
        public virtual ICollection<tb_pedido_venda> tb_pedido_venda { get; set; }
        public virtual ICollection<tb_salario> tb_salario { get; set; }
        public virtual ICollection<tb_taxa> tb_taxa { get; set; }
    }
}
