//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace food_truck.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_fornecedor
    {
        public tb_fornecedor()
        {
            this.tb_estoque = new HashSet<tb_estoque>();
            this.tb_logistica = new HashSet<tb_logistica>();
            this.tb_pedido_compra = new HashSet<tb_pedido_compra>();
        }
    
        public int id_fornecedor { get; set; }
        public string nm_Fornecedor { get; set; }
        public string nm_endereco { get; set; }
        public string nm_bairro { get; set; }
        public string nm_cidade { get; set; }
        public string tp_pessoaFJ { get; set; }
        public string tb_email { get; set; }
        public string razao_social { get; set; }
        public string doc_CNPJ { get; set; }
        public string tp_fornecimento { get; set; }
        public Nullable<System.DateTime> dt_Contrato { get; set; }
        public string tl_celular { get; set; }
        public string tl_fixo { get; set; }
    
        public virtual ICollection<tb_estoque> tb_estoque { get; set; }
        public virtual ICollection<tb_logistica> tb_logistica { get; set; }
        public virtual ICollection<tb_pedido_compra> tb_pedido_compra { get; set; }
    }
}
