//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace food_truck.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_holerite
    {
        public tb_holerite()
        {
            this.tb_salario = new HashSet<tb_salario>();
            this.tb_taxa = new HashSet<tb_taxa>();
        }
    
        public int id_holerite { get; set; }
        public Nullable<int> id_funcionario { get; set; }
        public Nullable<decimal> vl_bruto { get; set; }
        public Nullable<decimal> vl_liquido { get; set; }
        public Nullable<System.DateTime> dt_mes_e_ano { get; set; }
        public Nullable<decimal> vl_inss { get; set; }
        public Nullable<decimal> vl_fgts { get; set; }
        public Nullable<decimal> vl_ir { get; set; }
        public Nullable<System.TimeSpan> hr_extra { get; set; }
        public Nullable<decimal> vl_VTransporte { get; set; }
        public Nullable<decimal> vl_VRefeicao { get; set; }
        public Nullable<decimal> vl_VAlimentacao { get; set; }
        public Nullable<decimal> vl_impostoR { get; set; }
    
        public virtual tb_funcinario tb_funcinario { get; set; }
        public virtual ICollection<tb_salario> tb_salario { get; set; }
        public virtual ICollection<tb_taxa> tb_taxa { get; set; }
    }
}
