//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace food_truck.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_logistica
    {
        public int id_logistica { get; set; }
        public Nullable<int> id_produto { get; set; }
        public Nullable<int> id_fornecedor { get; set; }
        public string nm_produto { get; set; }
        public string nm_fornecedor { get; set; }
        public string ds_produto { get; set; }
        public Nullable<System.DateTime> tb_saida { get; set; }
        public Nullable<System.DateTime> tb_chegada { get; set; }
        public string lc_partida { get; set; }
        public string ed_fornecedor { get; set; }
    
        public virtual tb_produto tb_produto { get; set; }
        public virtual tb_fornecedor tb_fornecedor { get; set; }
    }
}
