//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace food_truck.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pedido_venda
    {
        public tb_pedido_venda()
        {
            this.tb_pedido_venda_item = new HashSet<tb_pedido_venda_item>();
        }
    
        public int id_pedidovenda { get; set; }
        public Nullable<int> id_funcionario { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<System.DateTime> dt_pedido { get; set; }
    
        public virtual tb_cliente tb_cliente { get; set; }
        public virtual tb_funcinario tb_funcinario { get; set; }
        public virtual ICollection<tb_pedido_venda_item> tb_pedido_venda_item { get; set; }
    }
}
