//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace food_truck.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pedido_venda_item
    {
        public int id_item { get; set; }
        public Nullable<int> id_pedidovenda { get; set; }
        public Nullable<int> id_produtovenda { get; set; }
        public Nullable<int> id_caixa { get; set; }
        public Nullable<int> qt_produto { get; set; }
    
        public virtual tb_caixa tb_caixa { get; set; }
        public virtual tb_pedido_venda tb_pedido_venda { get; set; }
        public virtual tb_produto_venda tb_produto_venda { get; set; }
    }
}
