//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace food_truck.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_produto_venda
    {
        public tb_produto_venda()
        {
            this.tb_pedido_venda_item = new HashSet<tb_pedido_venda_item>();
        }
    
        public int id_produtovenda { get; set; }
        public Nullable<int> id_produto { get; set; }
        public string nm_produto { get; set; }
        public string ds_produto { get; set; }
    
        public virtual ICollection<tb_pedido_venda_item> tb_pedido_venda_item { get; set; }
        public virtual tb_produto tb_produto { get; set; }
    }
}
