//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace food_truck.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_produto
    {
        public tb_produto()
        {
            this.tb_estoque = new HashSet<tb_estoque>();
            this.tb_logistica = new HashSet<tb_logistica>();
            this.tb_pedido_compra = new HashSet<tb_pedido_compra>();
            this.tb_pedido_compra_item = new HashSet<tb_pedido_compra_item>();
            this.tb_produto_venda = new HashSet<tb_produto_venda>();
        }
    
        public int id_produto { get; set; }
        public string nm_produto { get; set; }
        public string ds_produto { get; set; }
        public string nm_marca { get; set; }
        public Nullable<int> qtd_produto { get; set; }
        public Nullable<System.DateTime> dt_vencimento { get; set; }
        public Nullable<System.DateTime> dt_entrada { get; set; }
        public Nullable<decimal> prc_venda { get; set; }
        public Nullable<decimal> prc_custo { get; set; }
    
        public virtual ICollection<tb_estoque> tb_estoque { get; set; }
        public virtual ICollection<tb_logistica> tb_logistica { get; set; }
        public virtual ICollection<tb_pedido_compra> tb_pedido_compra { get; set; }
        public virtual ICollection<tb_pedido_compra_item> tb_pedido_compra_item { get; set; }
        public virtual ICollection<tb_produto_venda> tb_produto_venda { get; set; }
    }
}
