//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace food_truck.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_salario
    {
        public int id_salario { get; set; }
        public Nullable<int> id_funcionario { get; set; }
        public Nullable<int> id_holerite { get; set; }
        public Nullable<decimal> vl_salario { get; set; }
        public Nullable<System.TimeSpan> hr_extra { get; set; }
    
        public virtual tb_funcinario tb_funcinario { get; set; }
        public virtual tb_holerite tb_holerite { get; set; }
    }
}
